import { ArrowDown, ArrowUpRight, Instagram, MapPin } from 'lucide-react';
import { BRAND, METRICS } from '../config/brand';
import { CONTACT } from '../config/contact';
import { categories, projects } from '../data/projects';
import { testimonials } from '../data/testimonials';
import { CTA, Eyebrow, Media } from './UI';
export function Hero() {
  return <section id="inicio" className="hero"><Media src={BRAND.hero} alt="Poços de Caldas" className="hero-art" eager /><div className="hero-grain" />{BRAND.logo && <div className="hero-watermark" aria-hidden="true"><img src={BRAND.logo} alt="" /></div>}<div className="hero-content container"><Eyebrow><span className="tiny-line" /> UM OLHAR LOCAL. INFINITAS DESCOBERTAS.</Eyebrow><h1>Poços de Caldas<br />acontece <em>aqui.</em></h1><p className="hero-description">Conectamos pessoas aos lugares, sabores e experiências que fazem parte de Poços de Caldas.</p><p className="hero-secondary">E ajudamos negócios locais a chegarem a quem realmente quer descobri-los.</p><div className="hero-actions"><CTA light>Divulgue seu negócio</CTA><a href="#trabalhos" className="text-link">Conheça nosso trabalho <ArrowUpRight size={18} /></a></div></div><div className="hero-bottom container"><span><MapPin size={14} /> POÇOS DE CALDAS, MINAS GERAIS</span><a href="#manifesto" aria-label="Descubra mais sobre o Onde Ir">UM CONVITE À DESCOBERTA <ArrowDown size={16} /></a></div><span className="hero-side" aria-hidden="true">DESCUBRA. EXPERIMENTE. COMPARTILHE.</span></section>;
}
export function Positioning() {
  return <section id="manifesto" className="section container positioning reveal"><div><Eyebrow>A CIDADE É O NOSSO PONTO DE ENCONTRO</Eyebrow><h2>Mais do que<br />mostrar <em>onde ir.</em></h2></div><div className="position-copy"><p>O Onde Ir Poços de Caldas nasceu para conectar pessoas à cidade. Restaurantes, experiências, lojas, eventos e lugares que merecem ser descobertos ganham espaço através de conteúdos feitos para despertar curiosidade e vontade de conhecer.</p><p className="signature">A gente mostra. As pessoas descobrem.</p></div></section>;
}
export function Numbers() {
  return <section className="container numbers reveal" aria-label="Nossa comunidade"><div className="numbers-grid">{METRICS.map(m => <div key={m.label}><span className="metric-value">{m.value}</span><span>{m.label}</span></div>)}</div>{METRICS.some(m => m.pending) && <p className="pending-note">Indicadores em atualização. Os números oficiais serão disponibilizados em breve.</p>}</section>;
}
export function Discover() {
  return <section className="section container discover reveal"><div className="section-heading"><div><Eyebrow>VIVA A CIDADE COM A GENTE</Eyebrow><h2>Tem sempre algo novo<br />para <em>descobrir.</em></h2></div><a href={CONTACT.instagram} className="text-link" target="_blank" rel="noopener noreferrer">Veja mais no Instagram <ArrowUpRight size={18} /></a></div><div className="discovery-grid">{categories.map((c, i) => <Media key={c.name} src={c.image} alt={c.name + ' em Poços de Caldas'} className={`category category-${i}`}><div className="category-caption"><span className="category-index">0{i + 1}</span><h3>{c.name}</h3><p>{c.detail}</p></div></Media>)}</div></section>;
}
export function Portfolio() {
  return <section id="trabalhos" className="section container reveal"><div className="section-heading"><div><Eyebrow>NOSSAS HISTÓRIAS PELA CIDADE</Eyebrow><h2>Negócios que já<br />passaram <em>por aqui.</em></h2></div><p>Cada lugar tem uma história.<br />Nosso trabalho é ajudar a contá-la.</p></div><div className="portfolio-grid">{projects.length ? projects.map(p => <a key={p.name} href={p.instagram || CONTACT.instagram} target="_blank" rel="noopener noreferrer"><Media src={p.image} alt={p.name}><div className="project-caption"><span>{p.category} · {p.format}</span><h3>{p.name}</h3><ArrowUpRight /></div></Media></a>) : ['Um lugar. Uma história.', 'Uma experiência que conecta.', 'Uma nova descoberta.'].map((title, i) => <Media key={title} className={`portfolio-placeholder tone-${i}`}><div className="project-caption"><span>ESPAÇO PARA TRABALHO REAL</span><h3>{title}</h3></div></Media>)}</div>{!projects.length && <p className="pending-note">Portfólio em preparação. Conheça as divulgações no <a href={CONTACT.instagram} target="_blank" rel="noopener noreferrer">Instagram da marca <ArrowUpRight size={13} /></a>.</p>}</section>;
}
export function Testimonials() {
  return <section className="testimonials"><div className="container reveal"><Eyebrow>CONEXÕES QUE FAZEM SENTIDO</Eyebrow><h2>Quem já divulgou, <em>conta.</em></h2><div className="quotes">{testimonials.length ? testimonials.map(t => <figure key={t.name}><blockquote>“{t.quote}”</blockquote><figcaption>{t.name}<span>{t.business}</span></figcaption></figure>) : <div className="quote-pending"><span aria-hidden="true">“</span><p>Um espaço para as histórias de quem cresce junto com a gente.<small>Depoimentos de clientes em breve.</small></p></div>}</div></div></section>;
}
export function About() {
  return <section id="sobre" className="section container about reveal"><Media src={BRAND.about} alt={BRAND.creator ? `Retrato de ${BRAND.creator}` : 'Conteúdo do Onde Ir Poços de Caldas'} className="about-media"><span className="about-art-text" aria-hidden="true">Um olhar<br /><em>daqui.</em></span><span className="about-stamp"><MapPin size={23} /> FEITO DE ENCONTROS<br />E BOAS DESCOBERTAS</span></Media><div><Eyebrow>FEITO POR QUEM VIVE A CIDADE</Eyebrow><h2>Por trás<br />do <em>Onde Ir.</em></h2><p>O Onde Ir Poços de Caldas nasceu da vontade de descobrir e compartilhar tudo que a cidade tem de especial. Ao longo do caminho, virou também uma ponte entre bons negócios e pessoas procurando novas experiências.</p>{BRAND.creator && <h3>{BRAND.creator}</h3>}{BRAND.story && <p>{BRAND.story}</p>}<p className="signature">Um olhar curioso. Uma conexão de verdade.</p><a href={CONTACT.instagram} target="_blank" rel="noopener noreferrer" className="text-link">Vem conhecer a gente <ArrowUpRight size={18} /></a></div></section>;
}
export function InstagramSection() {
  return <section className="instagram-section"><div className="container reveal"><div className="section-heading"><div><Eyebrow><Instagram size={16} /> @ONDEIRPOCOSDECALDAS</Eyebrow><h2>A cidade continua<br />no <em>Instagram.</em></h2></div><div><p>Novos lugares, bons encontros e aquela<br />vontade de conhecer. Acompanhe de perto.</p><a className="text-link" href={CONTACT.instagram} target="_blank" rel="noopener noreferrer">Seguir @ondeirpocosdecaldas <ArrowUpRight size={18} /></a></div></div><div className="instagram-grid">{categories.slice(0, 4).map((c, i) => <a key={c.name} href={CONTACT.instagram} target="_blank" rel="noopener noreferrer" aria-label={`Descobrir ${c.name.toLowerCase()} no Instagram`}><Media src={c.image} alt={c.name} className={`feed-tile tone-${i}`}><Instagram size={20} /><span>{c.name}</span></Media></a>)}</div></div></section>;
}
