import { useState } from 'react';
import { Plus, ArrowUpRight } from 'lucide-react';
import { useEstablishments } from '../../hooks/useEstablishments';
import { campaignStatus } from '../../utils/establishments';
import { daysRemaining, formatDate } from '../../utils/dates';
import { resetMockData } from '../../services/establishmentsService';
import ConfirmModal from '../../components/admin/ConfirmModal';
import { isMockMode } from '../../lib/supabase';
export default function DashboardPage() {
  const { items, loading, error } = useEstablishments();
  const [reset, setReset] = useState(false), [message, setMessage] = useState('');
  const ending = items.filter(item => campaignStatus(item) === 'ATIVO' && item.endDate && daysRemaining(item.endDate) <= 30).sort((a, b) => a.endDate.localeCompare(b.endDate));
  return <><div className="admin-title"><div><p className="eyebrow">VISÃO GERAL</p><h1>Boas descobertas começam aqui.</h1><p>Acompanhe os cadastros e o período de cada divulgação.</p></div><a className="admin-button" href="/admin/establishments/new"><Plus size={18} />Novo estabelecimento</a></div>{error && <p role="alert" className="admin-error">{error}</p>}{loading ? <p role="status">Carregando resumo…</p> : <><div className="dashboard-metrics">{[['Total de estabelecimentos', items.length], ...[['Ativos', 'ATIVO'], ['Inativos', 'INATIVO'], ['Agendados', 'AGENDADO'], ['Expirados', 'EXPIRADO']].map(([label, status]) => [label, items.filter(item => campaignStatus(item) === status).length])].map(([label, count]) => <article key={label}><span>{label}</span><strong>{count}</strong></article>)}</div><section className="admin-panel"><div className="admin-title"><div><h2>Campanhas próximas do vencimento</h2><p>Divulgações ativas que terminam nos próximos 30 dias.</p></div></div>{ending.length ? <div className="expiring-list">{ending.map(item => <a href={`/admin/establishments/${item.id}/edit`} key={item.id}><strong>{item.name}</strong><span>{formatDate(item.endDate)}</span><span>{daysRemaining(item.endDate) === 0 ? 'Termina hoje' : `${daysRemaining(item.endDate)} dias restantes`}</span><ArrowUpRight size={18} /></a>)}</div> : <p className="admin-empty">Nenhuma campanha próxima do vencimento.</p>}</section></>}{isMockMode && <button className="admin-link" onClick={() => setReset(true)}>Restaurar dados de demonstração</button>}{message && <p role="status">{message}</p>}{reset && <ConfirmModal title="Restaurar demonstração?" onCancel={() => setReset(false)} confirmLabel="Restaurar" onConfirm={async () => { try { await resetMockData(); setReset(false); setMessage('Os seis cadastros de demonstração foram restaurados.'); } catch (e) { setMessage(e.message); } }}><p>Os cadastros e imagens deste navegador serão substituídos pelos seis exemplos iniciais.</p></ConfirmModal>}</>;
}
